server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          uri: https://gitlab.com/......................
          clone-on-start: false
