spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-ms
          uri: lb://product-ms
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: user-ms
          uri: lb://user-ms
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
